apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-eviamfvx
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-eviamfvx:94e94ca02a10ba5debd557c0a260dc381e704272@sha256:dc8a6b33493b5f27debf98497cf98eda77f854124a95ae888b72900e8a166c8a
          name: container-image
